/* eslint-disable */ 
<template>
<div class="row">
    <div class="col-12">
<p>Wir informieren Sie nachfolgend gemäß den gesetzlichen Vorgaben des Datenschutzrechts (insb. gemäß BDSG n.F. und der europäischen Datenschutz-Grundverordnung ‚DS-GVO‘) über die Art, den Umfang und Zweck der Verarbeitung personenbezogener Daten durch unser Unternehmen. Diese Datenschutzerklärung gilt auch für unsere Websites und Sozial-Media-Profile. Bezüglich der Definition von Begriffen wie etwa „personenbezogene Daten“ oder „Verarbeitung“ verweisen wir auf Art. 4 DS-GVO.</p>
					<strong>Name und Kontaktdaten des / der Verantwortlichen</strong><br />
					Unser/e Verantwortliche/r (nachfolgend „Verantwortlicher“) i.S.d. Art. 4 Zif. 7 DS-GVO ist:<br />
					<br />Macolor<br />Gartenstr. 17d<br />97422, Schweinfurt, Deutschland<br />E-Mail-Adresse: hello@macolor.com<br /><br /><strong>Datenarten, Zwecke der Verarbeitung und Kategorien betroffener Personen</strong><br />
        <p>Nachfolgend informieren wir Sie über Art, Umfang und Zweck der Erhebung, Verarbeitung und Nutzung personenbezogener Daten.</p>
        <strong>1. Arten der Daten, die wir verarbeiten</strong><br />Nutzungsdaten (Zugriffszeiten, besuchte Websites etc.), Kontaktdaten (Telefonnummer, E-Mail, Fax etc.), <br />
        <br />
        <strong>2. Zwecke der Verarbeitung nach Art. 13 Abs. 1 c) DS-GVO</strong><br />Website technisch und wirtschaftlich optimieren, Leichten Zugang zur Website ermöglichen, Optimierung und statistische Auswertung unserer Dienste, Nutzererfahrung verbessern, Website benutzerfreundlich gestalten, Marketing / Vertrieb / Werbung, Erstellung von Statistiken, Kontaktanfragen abwickeln, Websites mit Funktionen und Inhalten bereitstellen, <br />
        <br />
        <strong>3. Kategorien der betroffenen Personen nach Art. 13 Abs. 1 e) DS-GVO</strong><br />Besucher/Nutzer der Website, Interessenten, <br />
        <br />
        <p>Die betroffenen Personen werden zusammenfassend als „Nutzer“ bezeichnet.</p>
        <br />

        <strong>Rechtsgrundlagen der Verarbeitung personenbezogener Daten</strong>
        <p>Nachfolgend Informieren wir Sie über die Rechtsgrundlagen der Verarbeitung personenbezogener Daten:</p>
        <ol style="margin:10px 0px; padding:15px;">
            <li>Wenn wir Ihre Einwilligung für die Verarbeitung personenbezogenen Daten eingeholt haben, ist Art. 6 Abs. 1 S. 1 lit. a) DS-GVO Rechtsgrundlage.</li>
            <li>Ist die Verarbeitung zur Erfüllung eines Vertrags oder zur Durchführung vorvertraglicher Maßnahmen erforderlich, die auf Ihre Anfrage hin erfolgen, so ist Art. 6 Abs. 1 S. 1 lit. b) DS-GVO Rechtsgrundlage.</li>
            <li>Ist die Verarbeitung zur Erfüllung einer rechtlichen Verpflichtung erforderlich, der wir unterliegen (z.B. gesetzliche Aufbewahrungspflichten), so ist Art. 6 Abs. 1 S. 1 lit. c) DS-GVO Rechtsgrundlage.</li>
            <li>Ist die Verarbeitung erforderlich, um lebenswichtige Interessen der betroffenen Person oder einer anderen natürlichen Person zu schützen, so ist Art. 6 Abs. 1 S. 1 lit. d) DS-GVO Rechtsgrundlage.</li>
            <li>Ist die Verarbeitung zur Wahrung unserer oder der berechtigten Interessen eines Dritten erforderlich und überwiegen diesbezüglich Ihre Interessen oder Grundrechte und Grundfreiheiten nicht, so ist Art. 6 Abs. 1 S. 1 lit. f) DS-GVO Rechtsgrundlage.</li>
        </ol>
        <br />
        <strong>Weitergabe personenbezogener Daten an Dritte und Auftragsverarbeiter</strong>
        <p>Ohne Ihre Einwilligung geben wir grundsätzlich keine Daten an Dritte weiter. Sollte dies doch der Fall sein, dann erfolgt die Weitergabe auf der Grundlage der zuvor genannten Rechtsgrundlagen z.B. bei der Weitergabe von Daten an Online-Paymentanbieter zur Vertragserfüllung oder aufgrund gerichtlicher Anordnung oder wegen einer gesetzlichen Verpflichtung zur Herausgabe der Daten zum Zwecke der Strafverfolgung, zur Gefahrenabwehr oder zur Durchsetzung der Rechte am geistigen Eigentum.<br />
            Wir setzen zudem Auftragsverarbeiter (externe Dienstleister z.B. zum Webhosting unserer Websites und Datenbanken) zur Verarbeitung Ihrer Daten ein. Wenn im Rahmen einer Vereinbarung zur Auftragsverarbeitung an die Auftragsverarbeiter Daten weitergegeben werden, erfolgt dies immer nach Art. 28 DS-GVO. Wir wählen dabei unsere Auftragsverarbeiter sorgfältig aus, kontrollieren diese regelmäßig und haben uns ein Weisungsrecht hinsichtlich der Daten einräumen lassen. Zudem müssen die Auftragsverarbeiter geeignete technische und organisatorische Maßnahmen getroffen haben und die Datenschutzvorschriften gem. BDSG n.F. und DS-GVO einhalten</p>

        <br />
        <strong>Datenübermittlung in Drittstaaten</strong>
        <p>Durch die Verabschiedung der europäischen Datenschutz-Grundverordnung (DS-GVO) wurde eine einheitliche Grundlage für den Datenschutz in Europa geschaffen. Ihre Daten werden daher vorwiegend durch Unternehmen verarbeitet, für die DS-GVO Anwendung findet. Sollte doch die Verarbeitung durch Dienste Dritter außerhalb der Europäischen Union oder des Europäischen Wirtschaftsraums stattfinden, so müssen diese die besonderen Voraussetzungen der Art. 44 ff. DS-GVO erfüllen. Das bedeutet, die Verarbeitung erfolgt aufgrund besonderer Garantien, wie etwa die von der EU-Kommission offiziell anerkannte Feststellung eines der EU entsprechenden Datenschutzniveaus oder der Beachtung offiziell anerkannter spezieller vertraglicher Verpflichtungen, der so genannten „Standardvertragsklauseln“. Bei US-Unternehmen erfüllt die Unterwerfung unter das sog. „Privacy-Shield“, dem Datenschutzabkommen zwischen der EU und den USA, diese Voraussetzungen.</p>

        <br />
        <strong>Löschung von Daten und Speicherdauer</strong>
        <p>Sofern nicht in dieser Datenschutzerklärung ausdrücklich angegeben, werden Ihre personenbezogen Daten gelöscht oder gesperrt, sobald der Zweck für die Speicherung entfällt, es sei denn deren weitere Aufbewahrung ist zu Beweiszwecken erforderlich oder dem stehen gesetzliche Aufbewahrungspflichten entgegenstehen. Darunter fallen etwa handelsrechtliche Aufbewahrungspflichten von Geschäftsbriefen nach § 257 Abs. 1 HGB (6 Jahre) sowie steuerrechtliche Aufbewahrungspflichten nach § 147 Abs. 1 AO von Belegen (10 Jahre). Wenn die vorgeschriebene Aufbewahrungsfrist abläuft, erfolgt eine Sperrung oder Löschung Ihrer Daten, es sei denn die Speicherung ist weiterhin für einen Vertragsabschluss oder zur Vertragserfüllung erforderlich.</p>

        <br/>
        <strong>Bestehen einer automatisierten Entscheidungsfindung</strong>
        <p>Wir setzen keine automatische Entscheidungsfindung oder ein Profiling ein.</p>

        <br/>
        <strong>Bereitstellung unserer Website und Erstellung von Logfiles</strong>
        <ol style="margin:10px 0px; padding:15px;">
             <li>Wenn Sie unsere Webseite lediglich informatorisch nutzen (also keine Registrierung und auch keine anderweitige Übermittlung von Informationen), erheben wir nur die personenbezogenen Daten, die Ihr Browser an unseren Server übermittelt. Wenn Sie unsere Website betrachten möchten, erheben wir die folgenden Daten:
            • IP-Adresse;<br />
            • Internet-Service-Provider des Nutzers;<br />
            • Datum und Uhrzeit des Abrufs;<br />
            • Browsertyp;<br />
            • Sprache und Browser-Version;<br />
            • Inhalt des Abrufs;<br />
            • Zeitzone;<br />
            • Zugriffsstatus/HTTP-Statuscode;<br />
            • Datenmenge;<br />
            • Websites, von denen die Anforderung kommt;<br />
            • Betriebssystem.<br />
            Eine Speicherung dieser Daten zusammen mit anderen personenbezogenen Daten von Ihnen findet nicht statt.<br /><br />
             </li>
            <li>Diese Daten dienen dem Zweck der nutzerfreundlichen, funktionsfähigen und sicheren Auslieferung unserer Website an Sie mit Funktionen und Inhalten sowie deren Optimierung und statistischen Auswertung.<br /><br /></li>
            <li>Rechtsgrundlage hierfür ist unser in den obigen Zwecken auch liegendes berechtigtes Interesse an der Datenverarbeitung nach Art. 6 Abs. 1 S.1 lit. f)  DS-GVO.<br /><br /></li>
            <li>Wir speichern aus Sicherheitsgründen diese Daten in Server-Logfiles für die Speicherdauer von  Tagen. Nach Ablauf dieser Frist werden diese automatisch gelöscht, es sei denn wir benötigen deren Aufbewahrung zu Beweiszwecken bei Angriffen auf die Serverinfrastruktur oder anderen Rechtsverletzungen.<br /></li>
        </ol><br/>
			<strong>Cookies</strong>
			<ol style="margin:10px 0px; padding:15px;">
				<li>Wir verwenden sog. Cookies bei Ihrem Besuch unserer Website. Cookies sind kleine Textdateien, die Ihr Internet-Browser auf Ihrem Rechner ablegt und speichert. Wenn Sie unsere Website erneut aufrufen, geben diese Cookies Informationen ab, um Sie automatisch wiederzuerkennen. Die so erlangten Informationen dienen dem Zweck, unsere Webangebote technisch und wirtschaftlich zu optimieren und Ihnen einen leichteren und sicheren Zugang auf unsere Website zu ermöglichen. Wir informieren Sie dazu beim Aufruf unserer Website mittels eines Hinweises auf unsere Datenschutzerklärung über die Verwendung von Cookies zu den zuvor genannten Zwecken und wie Sie dieser widersprechen bzw. deren Speicherung verhindern können („Opt-out“). Unsere Website nutzt Session-Cookies, persistente Cookies und Cookies von Drittanbietern:<br /><br />
					<strong>• Session-Cookies:</strong> Wir verwenden sog. Cookies zum Wiedererkennen mehrfacher Nutzung eines Angebots durch denselben Nutzer (z.B. wenn Sie sich eingeloggt haben zur Feststellung Ihres Login-Status). Wenn Sie unsere Seite erneut aufrufen, geben diese Cookies Informationen ab, um Sie automatisch wiederzuerkennen. Die so erlangten Informationen dienen dazu, unsere Angebote zu optimieren und Ihnen einen leichteren Zugang auf unsere Seite zu ermöglichen. Wenn Sie den Browser schließen oder Sie sich ausloggen, werden die Session-Cookies gelöscht.<br /><br />
					<strong>• Persistente Cookies:</strong> Diese werden automatisiert nach einer vorgegebenen Dauer gelöscht, die sich je nach Cookie unterscheiden kann. In den Sicherheitseinstellungen Ihres Browsers können Sie die Cookies jederzeit löschen.<br /><br />
					<strong>• Cookies von Drittanbietern (Third-Party-Cookies):</strong> Entsprechend Ihren Wünschen können Sie können Ihre Browser-Einstellung konfigurieren und z. B. Die Annahme von Third-Party-Cookies oder allen Cookies ablehnen. Wir weisen Sie jedoch an dieser Stelle darauf hin, dass Sie dann eventuell nicht alle Funktionen dieser Website nutzen können. Lesen Sie Näheres zu diesen Cookies bei den jeweiligen Datenschutzerklärungen zu den Drittanbietern.<br /><br />
				</li>
				<li>Rechtsgrundlage dieser Verarbeitung ist Art. 6 Abs. 1 S. lit. b) DS-GVO, wenn die Cookies zur Vertragsanbahnung z.B. bei Bestellungen gesetzt werden und ansonsten haben wir ein berechtigtes Interesse an der effektiven Funktionalität der Website, so dass in dem Falle Art. 6 Abs. 1 S. 1 lit. f) DS-GVO Rechtsgrundlage ist.<br /><br /></li>
				<li><strong>Widerspruch und „Opt-Out“:</strong>      Das Speichern von Cookies auf Ihrer Festplatte können Sie allgemein verhindern, indem Sie in Ihren Browser-Einstellungen „keine Cookies akzeptieren“ wählen. Dies kann aber eine Funktionseinschränkung unserer Angebote zur Folge haben. Sie können dem Einsatz von Cookies von Drittanbietern zu Werbezwecken über ein sog. „Opt-out“ über diese amerikanische Website (<a href="https://optout.aboutads.info" rel="nofollow" target="_blank">https://optout.aboutads.info</a>) oder diese europäische Website (<a href="http://www.youronlinechoices.com/de/praferenzmanagement/" rel="nofollow" target="_blank">http://www.youronlinechoices.com/de/praferenzmanagement/</a>) widersprechen.</li>
			</ol><br/>
			<strong>Newsletter</strong>
			<ol style="margin:10px 0px; padding:15px;">
				<li>Unseren Newsletter können Sie mit Ihrer freiwilligen Einwilligung durch Eintragung Ihrer E-Mail-Adresse abonnieren. Nur diese ist Pflicht. Die Angabe weiterer Daten ist freiwillig und dient nur dem Zweck einer persönlichen Ansprache. Wir verwenden dabei zur Anmeldung das sog. „Double-Opt-in-Verfahren“. Nach Ihrer Anmeldung mit Ihrer E-Mail erhalten Sie von uns zur Bestätigung Ihrer Anmeldung eine E-Mail mit einem Link zur Bestätigung. Wenn Sie diesen Bestätigungslink klicken, wird Ihre E-Mail in den Newsletterverteiler aufgenommen und zum Zweck der Übersendung von E-Mails gespeichert. Sollten Sie den Klick auf den Bestätigungslink nicht innerhalb von 48 Stunden durchführen, werden Ihre Anmeldedaten gesperrt und nach 90 Tagen automatisch gelöscht. <br /><br /></li>
				<li>Zudem protokollieren wir Ihre bei der Anmeldung verwendete IP-Adresse sowie das Datum und die Uhrzeit des Double-Opt-ins (Anmeldung und Bestätigung). Zweck dieser Speicherung ist Erfüllung von rechtlichen Anforderungen hinsichtlich des Nachweises Ihrer Anmeldung sowie die Missbrauchsprävention hinsichtlich Ihrer E-Mail.<br /><br /></li>
				<li>Im Rahmen Ihrer Einwilligungserklärung werden die Inhalte (z.B. beworbene Produkte/Dienstleistungen, Angebote, Werbung und Themen) des Newsletters konkret beschrieben.<br /><br /></li><li>Wir nutzen zum E-Mail-Versand folgenden Versanddienstleister: <br />Mailchimp (), dessen Datenschutzerklärung finden Sie hier <a href="" rel="nofollow" target="_blank"></a>. Wir haben mit dem Versanddienstleister eine Vereinbarung zur Auftragsverarbeitung nach Art. 28 DS-GVO abgeschlossen.<br /><br /><li>Beim Versand des Newsletters werten wir Ihr Nutzerverhalten aus. Die Newsletter  beinhalten dafür sogenannte „Web-Beacons“ bzw. „Tracking-Pixel“, die beim Öffnen des Newsletters aufgerufen werden. Für die Auswertungen verknüpfen wir die Web-Beacons mit Ihrer E-Mail-Adresse und einer individuellen ID. Auch im Newsletter erhaltene Links enthalten diese ID. Die Daten werden ausschließlich pseudonymisiert erhoben, die IDs werden also nicht mit Ihren weiteren persönlichen Daten verknüpft, eine direkte Personenbeziehbarkeit wird ausgeschlossen. Mit diesen Daten können wir feststellen, ob und wann Sie den Newsletter geöffnet haben und welche Links im Newsletter geklickt worden sind. Dies dient dem Zweck der Optimierung und statistischen Auswertung unseres Newsletters.<br /><br /></li><li>Rechtsgrundlage für den Newsletterversand, Erfolgsmessung und die Speicherung der E-Mail ist Ihre Einwilligung gem. Art. 6 Abs. 1 S. 1 lit. a) DS-GVO i.V.m § 7 Abs. 2 Nr. 3 UWG und für die Protokollierung der Einwilligung Art. 6 Abs. 1 S. 1 lit. f) DS-GVO, da diese unserem berechtigten Interesse der juristischen Beweisbarkeit dient.<br /><br /></li>
				<li>Dem Tracking können Sie jederzeit widersprechen, indem Sie den Abmeldelink am Ende des Newsletters klicken. In dem Falle würde allerdings auch der Newsletterempfang beendet. Wenn Sie in Ihrer E-Mail-Software die Anzeige von Bildern deaktivieren, ist ein Tracking ebenfalls nicht möglich. Dies kann allerdings Einschränkungen hinsichtlich der Funktionen des Newsletters haben und enthaltene Bilder werden dann nicht angezeigt.<br /><br /></li>
				<li>Sie können Ihre Einwilligung in die Übersendung des Newsletters jederzeit widerrufen. Sie können den Widerruf durch Betätigung des Abmeldelinks am Ende des Newsletters, eine E-Mail oder Mitteilung an unsere obigen Kontaktdaten ausüben. Wir speichern Ihre Daten, solange Sie den Newsletter abonniert haben. Nach der Abmeldung werden Ihre Daten nur noch anonym zu statistischen Zwecken gespeichert.<br /><br /></li>
			</ol><br/>
            <strong>Google AdWords mit Conversion-Tracking</strong>
             <ol style="margin:10px 0px; padding:15px;">
                 <li>Wir nutzen den Dienst „AdWords mit Conversion-Tracking“ (Google Inc., 1600 Amphitheater Parkway, Mountainview, California 94043, USA), um auf Websites Dritter mittels Anzeige auf unsere Website aufmerksam zu machen. Wenn Sie auf eine Google-Anzeige von uns klicken, wird ein Cookie in Ihrem Browser gespeichert, welcher etwa 30 Tage gültig ist. Wenn Sie danach unsere Website aufrufen, können wir und auch Google anhand des Cookies auswerten, ob Sie unsere Website besucht haben und welche Seite Sie bei uns besucht haben. Hierüber erstellt Google eine Statistik. Der volle Umfang der Datenverarbeitung ist uns nicht bekannt. Die Daten werden auch in die USA übertragen und dort analysiert. Wenn Sie mit einem Google-Account eingeloggt sind, können durch AdWords die Daten Ihrem Account zugeordnet werden. Wenn Sie dies nicht wünschen, müssen Sie sich vor dem Besuch unserer Website ausloggen. Dieses Conversion-Tracking dient dem Zweck der Analyse, Optimierung und dem wirtschaftlichen Betrieb unserer Werbung und Website.<br /><br /></li>
                 <li>Rechtsgrundlage für die Verarbeitung Ihrer Daten ist unser berechtigtes Interesse an der Analyse, Optimierung und dem wirtschaftlichen Betrieb unserer Werbung und Website gemäß Art. 6 Abs. 1 S. 1 lit. f) DS-GVO. Google ist nach dem EU-US Privacy Shield zertifiziert: <a href="https://www.privacyshield.gov/EU-US-Framework" rel="nofollow" target="_blank">https://www.privacyshield.gov/EU-US-Framework</a>.<br /><br /></li>
                 <li>Sie können der Installation von Cookies durch Google auf verschiedene Arten widersprechen bzw. diese verhindern:<br /><br />
                     • Sie können die Cookies in Ihrem Browser durch die <strong>Einstellung “keine Cookies akzeptieren”</strong> unterbinden, was auch die Cookies von Drittanbietern beinhaltet;<br /><br />
                     • Sie können direkt bei Google über den Link <a href="https://adssettings.google.com" rel="nofollow" target="_blank">https://adssettings.google.com</a> das Conversion-Tracking deaktivieren, wobei diese Einstellung nur solange Bestand hat, bis Sie Ihre Cookies löschen.<br /><br />
                     • Sie können die personalisierten <strong>Anzeigen der Drittanbieter</strong>, die an der Werbeselbstregulierungsinitiaive “About Ads” teilnehmen über den Link <a href="https://optout.aboutads.info" rel="nofollow" target="_blank">https://optout.aboutads.info</a> für US-Seiten oder für EU-Seiten unter <a href="http://www.youronlinechoices.com/de/praferenzmanagement/" rel="nofollow" target="_blank">http://www.youronlinechoices.com/de/praferenzmanagement/</a> deaktivieren, wobei diese Einstellung nur solange Bestand hat, bis Sie all Ihre Cookies löschen;<br /><br />
                     • Sie können durch ein <strong>Browser-Plug-in</strong> für Chrome, Firefox oder Internet-Explorer unter dem Link <a href="https://support.google.com/ads/answer/7395996" rel="nofollow" target="_blank">https://support.google.com/ads/answer/7395996</a> dauerhaft Cookies deaktivieren. Diese Deaktivierung kann zur Folge haben, dass Sie nicht alle Funktionen unserer Website mehr vollumfänglich nutzen können.<br /><br />
                     <br />
                 </li>
                 <li>Weitere Informationen finden Sie in der Datenschutzerklärung von Google unter <a href="https://policies.google.com/privacy?hl=de&gl=de" rel="nofollow" target="_blank">https://policies.google.com/privacy?hl=de&gl=de</a> und <a href="https://services.google.com/sitestats/de.html" rel="nofollow" target="_blank">https://services.google.com/sitestats/de.html</a>.<br /><br /></li>
             </ol><br/>
            <strong>Google Analytics</strong>

            <ol style="margin:10px 0px; padding:15px;">
                <li>Wir haben das Webseitenanalyse-Tool „Google Analytics“ (Google Inc., 1600 Amphitheater Parkway, Mountainview, California 94043, USA, EU-Niederlassung: Google Dublin, Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Ireland) auf unserer Website integriert.<br /><br /></li>
                <li>Beim Besuch unserer Website setzt Google einen Cookie auf Ihren Computer, um die Benutzung unserer Website durch Sie analysieren zu können. Die gewonnenen Daten werden in die USA übertragen und dort gespeichert. Falls personenbezogen Daten in die USA übertragen werden sollten, bietet die Zertifizierung Googles gemäß Privacy-Shield-Abkommen (<a href="https://www.privacyshield.gov/EU-US-Framework" rel="nofollow" target="_blank">https://www.privacyshield.gov/EU-US-Framework</a>) die Garantie dafür, dass das europäische Datenschutzrecht eingehalten wird.<br /><br /></li>
                <li>Wir haben die IP-Anonymisierung „anonymizeIP“ aktiviert, wodurch die IP-Adressen nur gekürzt weiterverarbeitet werden. Auf dieser Webseite wird Ihre IP-Adresse von Google daher innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Webseite wird Google diese Informationen benutzen, um Ihre Nutzung der Webseite auszuwerten, um Reports über die Webseitenaktivitäten zusammenzustellen und um weitere, mit der Websitenutzung und der Internetnutzung verbundene, Dienstleistungen gegenüber dem Verantwortlichen zu erbringen. Wir haben darüber hinaus die geräteübergreifende Analyse von Website-Besuchern aktiviert, die über eine sog. User-ID durchgeführt wird. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Die Nutzung von Google Analytics dient dem Zweck der Analyse, Optimierung und Verbesserung unserer Website.<br /><br /></li>
                <li>Rechtsgrundlage hierfür ist unser in den obigen Zwecken auch liegendes berechtigtes Interesse an der Datenverarbeitung nach Art. 6 Abs. 1 S.1 lit. f)  DS-GVO.<br /><br /></li>
                <li>Die von uns gesendeten und mit Cookies, Nutzerkennungen (z. B. User-ID) oder Werbe-IDs verknüpften Daten werden nach  Monaten automatisch gelöscht. Die Löschung von Daten, deren Aufbewahrungsdauer erreicht ist, erfolgt automatisch einmal im Monat.<br /><br /></li>
                <li>Weitere Informationen zu Datennutzung bei Google Analytics finden Sie hier: <a href="https://www.google.com/analytics/terms/de.html" rel="nofollow" target="_blank">https://www.google.com/analytics/terms/de.html</a> (Nutzungsbedingungen von Analytics), <a href="https://support.google.com/analytics/answer/6004245?hl=de" rel="nofollow" target="_blank">https://support.google.com/analytics/answer/6004245?hl=de</a> (Hinweise zum Datenschutz bei Analytics) und Googles Datenschutzerklärung <a href="https://policies.google.com/privacy" rel="nofollow" target="_blank">https://policies.google.com/privacy</a>.<br /><br /></li>
                <li>Widerspruch und „Opt-Out“: Das Speichern von Cookies auf Ihrer Festplatte können Sie allgemein verhindern, indem Sie in Ihren Browser-Einstellungen „keine Cookies akzeptieren“ wählen. Dies kann aber eine Funktionseinschränkung unserer Angebote zur Folge haben. Sie können darüber hinaus die Erfassung der, durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen, Daten an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren: <a href="http://tools.google.com/dlpage/gaoptout?hl=de" rel="nofollow" target="_blank">http://tools.google.com/dlpage/gaoptout?hl=de</a><br /><br /></li>
                <li>Als Alternative zum obigen Browser-Plugin können Sie die Erfassung durch Google Analytics unterbinden, indem Sie <strong>[__hier bitte__den Analytics Opt-Out Link Ihrer Webseite einfügen]</strong> klicken. Durch den Klick wird ein „Opt-out“-Cookie gesetzt, das die Erfassung Ihrer Daten beim Besuch dieser Webseite zukünftig verhindert. Dieses Cookie gilt nur für unsere Webseite und Ihren aktuellen Browser und hat nur solange Bestand bis Sie Ihre Cookies löschen. In dem Falle müssten Sie das Cookie erneut setzen.<br /><br /></li>
                <li>Die geräteübergreifende Nutzeranalyse können Sie in Ihrem Google-Account unter „Meine Daten > persönliche Daten“ deaktivieren.<br /><br /></li>
            </ol><br/>
            <strong>Präsenz in sozialen Medien</strong>

            <ol style="margin:10px 0px; padding:15px;">
                <li>Wir unterhalten in sozialen Medien Profile bzw. Fanpages, um mit den dort angeschlossenen und registrierten Nutzern zu kommunizieren und um über unsere Produkte, Angebote und Dienstleistungen zu informieren. Die US-Anbieter sind nach dem sog. Privacy-Shield zertifiziert und damit verpflichtet europäischen Datenschutz einzuhalten. Bei der Nutzung und dem Aufruf unseres Profils im jeweiligen Netzwerk durch Sie gelten die jeweiligen Datenschutzhinweise und Nutzungsbedingungen des jeweiligen Netzwerks.<br /><br /></li>
                <li>Wir verarbeiten Ihre Daten, die Sie uns über diese Netzwerke senden, um mit Ihnen zu kommunizieren und um Ihre dortigen Nachrichten zu beantworten.<br /><br /></li>
                <li>Die Rechtsgrundlage für die Verarbeitung der personenbezogenen Daten ist unser berechtigtes Interesse an der Kommunikation mit den Nutzern und unsere Außendarstellung zwecks Werbung gemäß Art. 6 Abs. 1 S. 1 lit. f) DS-GVO. Soweit Sie dem Verantwortlichen des sozialen Netzwerks eine Einwilligung in die Verarbeitung Ihrer personenbezogenen Daten erteilt haben, ist Rechtsgrundlage Art. 6 Abs. 1 S. 1 lit. a) und Art. 7 DS-GVO.<br /><br /></li>
                <li>Die Datenschutzhinweise, Auskunftsmöglichkeiten und Widerspruchmöglichkeiten (Opt-Out) der jeweiligen Netzwerke finden Sie hier:<br /><br />• <strong>Facebook</strong> (Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland)  Datenschutzerklärung: <a href="https://www.facebook.com/about/privacy/" rel="nofollow" target="_blank">https://www.facebook.com/about/privacy/</a>, Opt-Out: <a href="https://www.facebook.com/settings?tab=ads" rel="nofollow" target="_blank">https://www.facebook.com/settings?tab=ads</a> und <a href="http://www.youronlinechoices.com" rel="nofollow" target="_blank">http://www.youronlinechoices.com</a>, Privacy Shield: <a href="https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&status=Active" rel="nofollow" target="_blank">https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&status=Active</a>.<br /><br />• <strong>Instagram</strong> (Instagram Inc., 1601 Willow Road, Menlo Park, CA, 94025, USA) – Datenschutzerklärung/ Opt-Out: <a href="http://instagram.com/about/legal/privacy/" rel="nofollow" target="_blank">http://instagram.com/about/legal/privacy/</a>.<br /><br />• <strong>Twitter</strong> (Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA) - Datenschutzerklärung: <a href="https://twitter.com/de/privacy" rel="nofollow" target="_blank">https://twitter.com/de/privacy</a>, Opt-Out: <a href="https://twitter.com/personalization" rel="nofollow" target="_blank">https://twitter.com/personalization</a>, Privacy Shield: <a href="https://www.privacyshield.gov/participant?id=a2zt0000000TORzAAO&status=Active" rel="nofollow" target="_blank">https://www.privacyshield.gov/participant?id=a2zt0000000TORzAAO&status=Active</a>.<br /><br />• <strong>LinkedIn</strong> (LinkedIn Ireland Unlimited Company, Wilton Place, Dublin 2, Irland) – Datenschutzerklärung: <a href="https://www.linkedin.com/legal/privacy-policy" rel="nofollow" target="_blank">https://www.linkedin.com/legal/privacy-policy</a>, Cookie-Richtlinie und Opt-Out: <a href="https://www.linkedin.com/legal/cookie-policy" rel="nofollow" target="_blank">https://www.linkedin.com/legal/cookie-policy</a>, Privacy Shield der US-Firma LinkedIn Inc.: <a href="https://www.privacyshield.gov/participant?id=a2zt0000000L0UZAA0&status=Active" rel="nofollow" target="_blank">https://www.privacyshield.gov/participant?id=a2zt0000000L0UZAA0&status=Active</a>.<br /><br /></li>
            </ol><br/>
            <strong>Social-Media-Plug-ins</strong>

            <ol style="margin:10px 0px; padding:15px;">
                <li>Wir setzen auf unserer Webseite Social-Media-Plug-ins von sozialen Netzwerken ein. Dabei nutzen wir die sog. <strong>„Zwei-Klick-Lösung“-Shariff</strong> von c’t bzw. heise.de. Beim Abruf unserer Website werden dadurch <strong>keine personenbezogenen Daten</strong> an die Anbieter der Plug-ins übermittelt. Neben dem Logo bzw. der Marke des sozialen Netzwerks finden Sie einen Regler, mit dem Sie das Plug-in per Klick aktivieren können. Nach der Aktivierung erhält der Anbieter des sozialen Netzwerks die Information, dass Sie unsere Website aufgerufen haben und Ihre personenbezogenen Daten an den Anbieter des Plug-ins übermittelt und dort gespeichert werden. Hierbei handelt es sich um sog. Thirdparty Cookies. Bei einigen Anbietern wie Facebook und XING wird nach deren Angaben Ihre IP nach der Erhebung sofort anonymisiert.<br /><br /></li>
                <li>Die über den Nutzer erhobenen Daten speichert der Plug-in-Anbieter als Nutzungsprofile. Diese werden für Zwecke der Werbung, Marktforschung und/oder bedarfsgerechten Gestaltung seiner Website verwendet. Eine solche Auswertung erfolgt insbesondere (auch für nicht eingeloggte Nutzer) zur Darstellung von bedarfsgerechter Werbung und um andere Nutzer des sozialen Netzwerks über die Aktivitäten des Nutzers auf unserer Website zu informieren. Dem Nutzer steht ein Widerspruchsrecht gegen die Bildung dieser Nutzerprofile zu, wobei man sich zur Ausübung dieses Rechts an den jeweiligen Plug-in-Anbieter wenden muss.<br /><br /></li>
                <li>Rechtsgrundlage für die Nutzung der Plug-ins ist unser berechtigtes Interesse an der Verbesserung und Optimierung unserer Website durch die Steigerung unserer Bekanntheit mittels sozialer Netzwerke sowie die Möglichkeit der Interaktion mit Ihnen und der Nutzer untereinander über soziale Netzwerke gemäß Art. 6 Abs. 1 S.1 lit. f) DS-GVO.<br /><br /></li>
                <li>Auf die erhobenen Daten und Datenverarbeitungsvorgänge haben wir keinen Einfluss. Auch haben wir keine Kenntnis vom Umfang der Datenerhebung, vom Zweck der Verarbeitung und von den Speicherfristen. Auch zur Löschung der erhobenen Daten durch den Plug-in-Anbieter liegen uns keine Informationen vor.<br /><br /></li>
                <li>Wir verweisen hinsichtlich des Zwecks und Umfangs der Datenerhebung und Verarbeitung auf die jeweiligen Datenschutzerklärungen der sozialen Netzwerke. Zudem finden Sie dort auch Hinweise zu Ihren Rechten und Einstellungsmöglichkeiten zum Schutz Ihrer personenbezogenen Daten.<br /><br /></li>
            </ol><strong>Instagram</strong>
                <ol style="margin:10px 0px; padding:15px;">
                    <li>Wir haben auf unserer Website Plug-Ins vom sozialen Netzwerk Instagram (Instagram LLC., 1601 Willow Road, Menlo Park, CA, 94025, USA) im Rahmen der sog. „Zwei-Klick-Lösung“ von Shariff integriert. Diese erkennen Sie am Instagram-Logo in der Form einer viereckigen Kamera.<br /><br /></li>
                    <li>Wenn Sie willentlich das Plug-in aktivieren, wird hierbei eine Verbindung von Ihrem Browser zu den Servern von Instagram hergestellt. Dabei erhält Instagram die Information, einschließlich Ihrer IP-Adresse, dass Sie unsere Seite besucht haben und überträgt die Information an Server von Instagram in den USA, wo diese Information gespeichert wird. Wenn Sie bei Instagram in Ihren Account eingeloggt sind, kann Instagram diese Information Ihrem Account zuordnen und Sie können den Instagram-Button anklicken und so die Inhalte unserer Seiten auf Ihrem Instagram-Account teilen und speichern sowie ggf. Ihren dortigen Freunden anzeigen. Wir haben keine Kenntnis über den genauen Inhalt der übermittelten Daten, deren Nutzung und Speicherdauer durch Instagram.<br /><br /></li>
                    <li>Wenn Sie sich bei Instagram vor dem Besuch unserer Website ausloggen und Ihre Cookies löschen, werden bei der Aktivierung des Plug-ins keine Daten über den Besuch unserer Website Ihrem Profil auf Instagram zugeordnet.<br /><br /></li>
                    <li>Sie erhalten weitere Informationen in der Datenschutzerklärung von Instagram unter <a href="https://help.instagram.com/519522125107875" rel="nofollow" target="_blank">https://help.instagram.com/519522125107875</a> und zu den Einstellungen zum Schutz der Privatsphäre hier: <a href="https://help.instagram.com/196883487377501" rel="nofollow" target="_blank">https://help.instagram.com/196883487377501</a>.<br /><br /></li>
                </ol><br/>
        <strong>Rechte der betroffenen Person</strong>

        <ol style="margin:10px 0px; padding:15px;">
            <li><strong>Widerspruch oder Widerruf gegen die Verarbeitung Ihrer Daten<br /><br />
                Soweit die Verarbeitung auf Ihrer Einwilligung gemäß Art. 6 Abs. 1 S. 1 lit. a), Art. 7 DS-GVO beruht, haben Sie das Recht, die Einwilligung jederzeit zu widerrufen. Die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung wird dadurch nicht berührt.<br /><br />
                Soweit wir die Verarbeitung Ihrer personenbezogenen Daten auf die Interessenabwägung gemäß Art. 6 Abs. 1 S. 1 lit. f) DS-GVO stützen, können Sie Widerspruch gegen die Verarbeitung einlegen. Dies ist der Fall, wenn die Verarbeitung insbesondere nicht zur Erfüllung eines Vertrags mit Ihnen erforderlich ist, was von uns jeweils bei der nachfolgenden Beschreibung der Funktionen dargestellt wird. Bei Ausübung eines solchen Widerspruchs bitten wir um Darlegung der Gründe, weshalb wir Ihre personenbezogenen Daten nicht wie von uns durchgeführt verarbeiten sollten. Im Falle Ihres begründeten Widerspruchs prüfen wir die Sachlage und werden entweder die Datenverarbeitung einstellen bzw. anpassen oder Ihnen unsere zwingenden schutzwürdigen Gründe aufzeigen, aufgrund derer wir die Verarbeitung fortführen.<br /><br />
                Sie können der Verarbeitung Ihrer personenbezogenen Daten für Zwecke der Werbung und Datenanalyse jederzeit widersprechen. Das Widerspruchsrecht können Sie kostenfrei ausüben. Über Ihren Werbewiderspruch können Sie uns unter folgenden Kontaktdaten informieren:<br /><br />Macolor<br />Gartenstr. 17d<br />97422, Schweinfurt, Deutschland<br />E-Mail-Adresse: hello@macolor.com<br /></strong>
                	<br /></li>
					<li><strong>Recht auf Auskunft</strong><br />
						Sie haben das Recht, von uns eine Bestätigung darüber zu verlangen, ob Sie betreffende personenbezogene Daten verarbeitet werden. Sofern dies der Fall ist, haben Sie ein Recht auf Auskunft über Ihre bei uns gespeicherten persönlichen Daten nach Art. 15 DS-GVO. Dies beinhaltet insbesondere die Auskunft über die Verarbeitungszwecke, die Kategorie der personenbezogenen Daten, die Kategorien von Empfängern, gegenüber denen Ihre Daten offengelegt wurden oder werden, die geplante Speicherdauer, die Herkunft ihrer Daten, sofern diese nicht direkt bei Ihnen erhoben wurden.<br /><br /></li>
					<li><strong>Recht auf Berichtigung</strong><br />
						Sie haben ein Recht auf Berichtigung unrichtiger oder auf Vervollständigung richtiger Daten nach Art. 16 DS-GVO.
						<br /><br />
					</li>
					<li><strong>Recht auf Löschung</strong><br />
						Sie haben ein Recht auf Löschung Ihrer bei uns gespeicherten Daten nach Art. 17 DS-GVO, es sei denn gesetzliche oder vertraglichen Aufbewahrungsfristen oder andere gesetzliche Pflichten bzw. Rechte zur weiteren Speicherung stehen dieser entgegen.
						<br /><br />
					</li>
					<li><strong>Recht auf Einschränkung</strong><br />
						Sie haben das Recht, eine Einschränkung bei der Verarbeitung Ihrer personenbezogenen Daten zu verlangen, wenn eine der Voraussetzungen in Art. 18 Abs. 1 lit. a) bis d) DS-GVO erfüllt ist:<br />
						• Wenn Sie die Richtigkeit der Sie betreffenden personenbezogenen für eine Dauer bestreiten, die es dem Verantwortlichen ermöglicht, die Richtigkeit der personenbezogenen Daten zu überprüfen;<br /><br />
						• die Verarbeitung unrechtmäßig ist und Sie die Löschung der personenbezogenen Daten ablehnen und stattdessen die Einschränkung der Nutzung der personenbezogenen Daten verlangen;<br /><br />
						• der Verantwortliche die personenbezogenen Daten für die Zwecke der Verarbeitung nicht länger benötigt, Sie diese jedoch zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen benötigen, oder<br /><br />
						• wenn Sie Widerspruch gegen die Verarbeitung gemäß Art. 21 Abs. 1 DS-GVO eingelegt haben und noch nicht feststeht, ob die berechtigten Gründe des Verantwortlichen gegenüber Ihren Gründen überwiegen.<br /><br />
					</li>
					<li><strong>Recht auf Datenübertragbarkeit</strong><br />
						Sie haben ein Recht auf Datenübertragbarkeit nach Art. 20 DS-GVO, was bedeutet, dass Sie die bei uns über Sie gespeicherten personenbezogenen Daten in einem strukturierten, gängigen und maschinenlesbaren Format erhalten können oder die Übermittlung an einen anderen Verantwortlichen verlangen können.
						<br /><br />
					</li>
					<li><strong>Recht auf Beschwerde</strong><br />
						Sie haben ein Recht auf Beschwerde bei einer Aufsichtsbehörde. In der Regel können Sie sich hierfür an die Aufsichtsbehörde insbesondere in dem Mitgliedstaat ihres Aufenthaltsorts, ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes wenden.
						<br /><br />
					</li>
				</ol><br/>
					<strong>Datensicherheit</strong>
					<p>Um alle personenbezogen Daten, die an uns übermittelt werden, zu schützen und um sicherzustellen, dass die Datenschutzvorschriften von uns, aber auch unseren externen Dienstleistern eingehalten werden, haben wir geeignete technische und organisatorische Sicherheitsmaßnahmen getroffen. Deshalb werden unter anderem alle Daten zwischen Ihrem Browser und unserem Server über eine sichere SSL-Verbindung verschlüsselt übertragen.</p>
					<br />
			
					<br/>
					<strong>Stand: 06.10.2018</strong><p>Quelle: <a href="https://www.juraforum.de/impressum-generator/">Muster-Datenschutzerklärung von JuraForum.de</a></p>
</div>
</div>
                    </template>

<script>
export default {
    name: "DataPrivacy"
}
</script>
                    